import numpy as np
import matplotlib.pyplot as plt
import roboticstoolbox as rtb



def forward_kinematics(joint_angles):
    """
    Compute forward kinematics (FK) to transform joint angles into end-effector pose in Cartesian space.

    Parameters:
    - joint_angles: (batch_size, prediction_horizon, 7) -> 7 joint angles per arm

    Returns:
    - End-effector pose (batch_size, prediction_horizon, action_dim).
    """
    # load the URDF files for the left and right arms
    urdf = "/home/zhuoli/xtrainer_clover/assets/urdf/nova2_robot.urdf"
    xtrainer_arm = rtb.robot.ERobot.URDF(urdf)

    if joint_angles.ndim == 2:
        joint_angles = joint_angles[np.newaxis, :, :]  # Add batch dimension

    batch_size, prediction_horizon, _ = joint_angles.shape
    ee_position = np.zeros((batch_size, prediction_horizon, 3))  # (x, y, z)
    ee_orientations = np.zeros((batch_size, prediction_horizon, 3, 3))  # 3x3 rotation matrix

    for b in range(batch_size):
        for t in range(prediction_horizon):
            angles = joint_angles[b, t, :]
            T_left = xtrainer_arm.fkine(angles)
            T_left = np.array(T_left.A)
            ee_position[b, t, :] = T_left[:3, 3]
            ee_orientations[b, t, :, :] = T_left[:3, :3]

    return ee_position, ee_orientations



def visualize_trajectory(population_trajectories, best_trajectory):
    """
    Visualize the trajectories generated by Diffusion-ES.

    Parameters:
    - population_trajectories: (batch_size, prediction_horizon, 14)
      128 trajectories, each with 16 steps, 14 joint angles.
    - best_trajectory: (prediction_horizon, 14)
      The best trajectory (1 trajectory).
    """
    batch_size, prediction_horizon, action_dim = population_trajectories.shape

    # Separate left and right arm joint angles
    left_arm_trajectories = population_trajectories[:, :, :6]  # (batch_size, prediction_horizon, 7)
    right_arm_trajectories = population_trajectories[:, :, 7:13]  # (batch_size, prediction_horizon, 7)

    best_left_arm = best_trajectory[:, :6]  # (prediction_horizon, 7)
    best_right_arm = best_trajectory[:, 7:13]  # (prediction_horizon, 7)

    # Compute FK end-effector positions
    left_ee_positions, _ = forward_kinematics(left_arm_trajectories)
    right_ee_positions, _ = forward_kinematics(right_arm_trajectories)
    left_ee_positions = np.array(left_ee_positions)
    right_ee_positions = np.array(right_ee_positions)

    best_left_ee_positions, _ = forward_kinematics(best_left_arm)  # (prediction_horizon, 3)
    best_right_ee_positions, _ = forward_kinematics(best_right_arm)
    best_left_ee_positions = np.array(best_left_ee_positions)
    best_right_ee_positions = np.array(best_right_ee_positions)

    # Visualization of left and right arm trajectories
    fig = plt.figure(figsize=(12, 6))

    # Left arm trajectories
    ax1 = fig.add_subplot(121, projection='3d')
    for i in range(batch_size):
        ax1.plot(left_ee_positions[i, :, 0],
                 left_ee_positions[i, :, 1],
                 left_ee_positions[i, :, 2],
                 color="blue", alpha=0.2)  # Semi-transparent trajectories

    # Best trajectory (left arm)
    ax1.plot(best_left_ee_positions[0][:, 0],
             best_left_ee_positions[0][:, 1],
             best_left_ee_positions[0][:, 2],
             color="red", linewidth=2, label="Best Left Trajectory")

    # Mark start and end points for left arm
    ax1.scatter(best_left_ee_positions[0, 0, 0],  # Start X
                best_left_ee_positions[0, 0, 1],  # Start Y
                best_left_ee_positions[0, 0, 2],  # Start Z
                color='green', marker='o', s=100, label="Start Point")  # Green Start

    ax1.scatter(best_left_ee_positions[0, -1, 0],  # End X
                best_left_ee_positions[0, -1, 1],  # End Y
                best_left_ee_positions[0, -1, 2],  # End Z
                color='red', marker='X', s=150, label="End Point")  # Red End

    ax1.set_title("Left Arm End-Effector Trajectories")
    ax1.set_xlabel("X")
    ax1.set_ylabel("Y")
    ax1.set_zlabel("Z")
    ax1.legend()

    # Right arm trajectories
    ax2 = fig.add_subplot(122, projection='3d')
    for i in range(batch_size):
        ax2.plot(right_ee_positions[i, :, 0],
                 right_ee_positions[i, :, 1],
                 right_ee_positions[i, :, 2],
                 color="green", alpha=0.2)  # Semi-transparent trajectories

    # Best trajectory (right arm)
    ax2.plot(best_right_ee_positions[0][:, 0],
             best_right_ee_positions[0][:, 1],
             best_right_ee_positions[0][:, 2],
             color="red", linewidth=2, label="Best Right Trajectory")

    # Mark start and end points for right arm
    ax2.scatter(best_right_ee_positions[0, 0, 0],  # Start X
                best_right_ee_positions[0, 0, 1],  # Start Y
                best_right_ee_positions[0, 0, 2],  # Start Z
                color='green', marker='o', s=100, label="Start Point")  # Green Start

    ax2.scatter(best_right_ee_positions[0, -1, 0],  # End X
                best_right_ee_positions[0, -1, 1],  # End Y
                best_right_ee_positions[0, -1, 2],  # End Z
                color='red', marker='X', s=150, label="End Point")  # Red End

    ax2.set_title("Right Arm End-Effector Trajectories")
    ax2.set_xlabel("X")
    ax2.set_ylabel("Y")
    ax2.set_zlabel("Z")
    ax2.legend()

    plt.tight_layout()
    plt.show()


# def visualize_trajectory(population_trajectories, best_trajectory):
#     """
#     Visualize the trajectories generated by Diffusion-ES.
#
#     Parameters:
#     - population_trajectories: (batch_size, prediction_horizon, 14) # 128 trajectories, each with 16 steps, 14 joint angles
#     - best_trajectory: (prediction_horizon, 14) # The best trajectory (1 trajectory)
#     """
#     batch_size, prediction_horizon, action_dim = population_trajectories.shape
#
#     # Separate left and right arm joint angles
#     left_arm_trajectories = population_trajectories[:, :, :6]  # (batch_size, prediction_horizon, 7)
#     right_arm_trajectories = population_trajectories[:, :, 7:13]  # (batch_size, prediction_horizon, 7)
#
#     best_left_arm = best_trajectory[:, :6]  # (prediction_horizon, 7)
#     best_right_arm = best_trajectory[:, 7:13]  # (prediction_horizon, 7)
#
#     # Compute FK end-effector positions
#     left_ee_positions, _ = forward_kinematics(left_arm_trajectories)  # (batch_size, prediction_horizon, 3)
#     right_ee_positions, _ = forward_kinematics(right_arm_trajectories)
#     left_ee_positions = np.array(left_ee_positions)
#     right_ee_positions = np.array(right_ee_positions)
#
#     best_left_ee_positions, _ = forward_kinematics(best_left_arm)  # (prediction_horizon, 3)
#     best_right_ee_positions, _ = forward_kinematics(best_right_arm)
#     best_left_ee_positions = np.array(best_left_ee_positions)
#     best_right_ee_positions = np.array(best_right_ee_positions)
#
#     # Visualization of left and right arm trajectories
#     fig = plt.figure(figsize=(12, 6))
#
#     # Left arm trajectories
#     ax1 = fig.add_subplot(121, projection='3d')
#     for i in range(batch_size):
#         ax1.plot(left_ee_positions[i, :, 0],
#                  left_ee_positions[i, :, 1],
#                  left_ee_positions[i, :, 2],
#                  color="blue", alpha=0.2)  # Semi-transparent trajectories
#
#     # Best trajectory (left arm)
#     ax1.plot(best_left_ee_positions[0][:, 0],
#              best_left_ee_positions[0][:, 1],
#              best_left_ee_positions[0][:, 2],
#              color="red", linewidth=2, label="Best Left Trajectory")
#
#     ax1.set_title("Left Arm End-Effector Trajectories")
#     ax1.set_xlabel("X")
#     ax1.set_ylabel("Y")
#     ax1.set_zlabel("Z")
#     ax1.legend()
#
#     # Right arm trajectories
#     ax2 = fig.add_subplot(122, projection='3d')
#     for i in range(batch_size):
#         ax2.plot(right_ee_positions[i, :, 0],
#                  right_ee_positions[i, :, 1],
#                  right_ee_positions[i, :, 2],
#                  color="green", alpha=0.2)  # Semi-transparent trajectories
#
#     # Best trajectory (right arm)
#     ax2.plot(best_right_ee_positions[0][:, 0],
#              best_right_ee_positions[0][:, 1],
#              best_right_ee_positions[0][:, 2],
#              color="red", linewidth=2, label="Best Right Trajectory")
#
#     ax2.set_title("Right Arm End-Effector Trajectories")
#     ax2.set_xlabel("X")
#     ax2.set_ylabel("Y")
#     ax2.set_zlabel("Z")
#     ax2.legend()
#
#     plt.tight_layout()
#     plt.show()