import numpy as np
import matplotlib.pyplot as plt
import roboticstoolbox as rtb
import open3d as o3d
import transform_utils as T
from numba import njit
from ModelTrain.dp.utils import forward_kinematics

# def visualize_trajectory(population_trajectories, best_trajectory):
#     """
#     Visualize the trajectories generated by Diffusion-ES.
#
#     Parameters:
#     - population_trajectories: (batch_size, prediction_horizon, 14)
#       128 trajectories, each with 16 steps, 14 joint angles.
#     - best_trajectory: (prediction_horizon, 14)
#       The best trajectory (1 trajectory).
#     """
#     batch_size, prediction_horizon, action_dim = population_trajectories.shape
#
#     # Separate left and right arm joint angles
#     left_arm_trajectories = population_trajectories[:, :, :6]  # (batch_size, prediction_horizon, 7)
#     right_arm_trajectories = population_trajectories[:, :, 7:13]  # (batch_size, prediction_horizon, 7)
#
#     best_left_arm = best_trajectory[:, :6]  # (prediction_horizon, 7)
#     best_right_arm = best_trajectory[:, 7:13]  # (prediction_horizon, 7)
#
#     # Compute FK end-effector positions
#     left_ee_positions, _ = forward_kinematics(left_arm_trajectories)
#     right_ee_positions, _ = forward_kinematics(right_arm_trajectories)
#     left_ee_positions = np.array(left_ee_positions)
#     right_ee_positions = np.array(right_ee_positions)
#
#     best_left_ee_positions, _ = forward_kinematics(best_left_arm)  # (prediction_horizon, 3)
#     best_right_ee_positions, _ = forward_kinematics(best_right_arm)
#     best_left_ee_positions = np.array(best_left_ee_positions)
#     best_right_ee_positions = np.array(best_right_ee_positions)
#
#     # Visualization of left and right arm trajectories
#     fig = plt.figure(figsize=(12, 6))
#
#     # Left arm trajectories
#     ax1 = fig.add_subplot(121, projection='3d')
#     for i in range(batch_size):
#         ax1.plot(left_ee_positions[i, :, 0],
#                  left_ee_positions[i, :, 1],
#                  left_ee_positions[i, :, 2],
#                  color="blue", alpha=0.2)  # Semi-transparent trajectories
#
#     # Best trajectory (left arm)
#     ax1.plot(best_left_ee_positions[0][:, 0],
#              best_left_ee_positions[0][:, 1],
#              best_left_ee_positions[0][:, 2],
#              color="red", linewidth=2, label="Best Left Trajectory")
#
#     # Mark start and end points for left arm
#     ax1.scatter(best_left_ee_positions[0, 0, 0],  # Start X
#                 best_left_ee_positions[0, 0, 1],  # Start Y
#                 best_left_ee_positions[0, 0, 2],  # Start Z
#                 color='green', marker='o', s=100, label="Start Point")  # Green Start
#
#     ax1.scatter(best_left_ee_positions[0, -1, 0],  # End X
#                 best_left_ee_positions[0, -1, 1],  # End Y
#                 best_left_ee_positions[0, -1, 2],  # End Z
#                 color='red', marker='X', s=150, label="End Point")  # Red End
#
#     ax1.view_init(elev=10, azim=180)
#
#     ax1.set_title("Left Arm End-Effector Trajectories")
#     ax1.set_xlabel("X")
#     ax1.set_ylabel("Y")
#     ax1.set_zlabel("Z")
#     ax1.legend()
#
#     # Right arm trajectories
#     ax2 = fig.add_subplot(122, projection='3d')
#     for i in range(batch_size):
#         ax2.plot(right_ee_positions[i, :, 0],
#                  right_ee_positions[i, :, 1],
#                  right_ee_positions[i, :, 2],
#                  color="green", alpha=0.2)  # Semi-transparent trajectories
#
#     # Best trajectory (right arm)
#     ax2.plot(best_right_ee_positions[0][:, 0],
#              best_right_ee_positions[0][:, 1],
#              best_right_ee_positions[0][:, 2],
#              color="red", linewidth=2, label="Best Right Trajectory")
#
#     # Mark start and end points for right arm
#     ax2.scatter(best_right_ee_positions[0, 0, 0],  # Start X
#                 best_right_ee_positions[0, 0, 1],  # Start Y
#                 best_right_ee_positions[0, 0, 2],  # Start Z
#                 color='green', marker='o', s=100, label="Start Point")  # Green Start
#
#     ax2.scatter(best_right_ee_positions[0, -1, 0],  # End X
#                 best_right_ee_positions[0, -1, 1],  # End Y
#                 best_right_ee_positions[0, -1, 2],  # End Z
#                 color='red', marker='X', s=150, label="End Point")  # Red End
#
#     ax2.view_init(elev=10, azim=0)
#     ax2.set_title("Right Arm End-Effector Trajectories")
#     ax2.set_xlabel("X")
#     ax2.set_ylabel("Y")
#     ax2.set_zlabel("Z")
#     ax2.legend()
#
#     plt.tight_layout()
#     plt.show()

def visualize_trajectory(left_ee_positions, right_ee_positions, best_trajectory):
    """
    Visualize the trajectories generated by Diffusion-ES.

    Parameters:
    - population_trajectories: (batch_size, prediction_horizon, 14)
      128 trajectories, each with 16 steps, 14 joint angles.
    - best_trajectory: (prediction_horizon, 14)
      The best trajectory (1 trajectory).
    """
    # batch_size, prediction_horizon, action_dim = population_trajectories.shape
    #
    # # Separate left and right arm joint angles
    # left_arm_trajectories = population_trajectories[:, :, :6]  # (batch_size, prediction_horizon, 7)
    # right_arm_trajectories = population_trajectories[:, :, 7:13]  # (batch_size, prediction_horizon, 7)
    #

    #
    # # Compute FK end-effector positions
    # left_ee_positions, _ = forward_kinematics(left_arm_trajectories)
    # right_ee_positions, _ = forward_kinematics(right_arm_trajectories)
    # left_ee_positions = np.array(left_ee_positions)
    # right_ee_positions = np.array(right_ee_positions)

    batch_size = left_ee_positions.shape[0]

    best_left_arm = best_trajectory[:, :6]  # (prediction_horizon, 7)
    best_right_arm = best_trajectory[:, 7:13]  # (prediction_horizon, 7)
    best_left_ee_positions, _ = forward_kinematics(best_left_arm)  # (prediction_horizon, 3)
    best_right_ee_positions, _ = forward_kinematics(best_right_arm)
    best_left_ee_positions = np.array(best_left_ee_positions)
    best_right_ee_positions = np.array(best_right_ee_positions)

    # Visualization of left and right arm trajectories
    fig = plt.figure(figsize=(12, 6))

    # Left arm trajectories
    ax1 = fig.add_subplot(121, projection='3d')
    for i in range(batch_size):
        ax1.plot(left_ee_positions[i, :, 0],
                 left_ee_positions[i, :, 1],
                 left_ee_positions[i, :, 2],
                 color="blue", alpha=0.2)  # Semi-transparent trajectories

    # Best trajectory (left arm)
    ax1.plot(best_left_ee_positions[0][:, 0],
             best_left_ee_positions[0][:, 1],
             best_left_ee_positions[0][:, 2],
             color="red", linewidth=2, label="Best Left Trajectory")

    # Mark start and end points for left arm
    ax1.scatter(best_left_ee_positions[0, 0, 0],  # Start X
                best_left_ee_positions[0, 0, 1],  # Start Y
                best_left_ee_positions[0, 0, 2],  # Start Z
                color='green', marker='o', s=100, label="Start Point")  # Green Start

    ax1.scatter(best_left_ee_positions[0, -1, 0],  # End X
                best_left_ee_positions[0, -1, 1],  # End Y
                best_left_ee_positions[0, -1, 2],  # End Z
                color='red', marker='X', s=150, label="End Point")  # Red End

    ax1.view_init(elev=10, azim=180)

    ax1.set_title("Left Arm End-Effector Trajectories")
    ax1.set_xlabel("X")
    ax1.set_ylabel("Y")
    ax1.set_zlabel("Z")
    ax1.legend()

    # Right arm trajectories
    ax2 = fig.add_subplot(122, projection='3d')
    for i in range(batch_size):
        ax2.plot(right_ee_positions[i, :, 0],
                 right_ee_positions[i, :, 1],
                 right_ee_positions[i, :, 2],
                 color="green", alpha=0.2)  # Semi-transparent trajectories

    # Best trajectory (right arm)
    ax2.plot(best_right_ee_positions[0][:, 0],
             best_right_ee_positions[0][:, 1],
             best_right_ee_positions[0][:, 2],
             color="red", linewidth=2, label="Best Right Trajectory")

    # Mark start and end points for right arm
    ax2.scatter(best_right_ee_positions[0, 0, 0],  # Start X
                best_right_ee_positions[0, 0, 1],  # Start Y
                best_right_ee_positions[0, 0, 2],  # Start Z
                color='green', marker='o', s=100, label="Start Point")  # Green Start

    ax2.scatter(best_right_ee_positions[0, -1, 0],  # End X
                best_right_ee_positions[0, -1, 1],  # End Y
                best_right_ee_positions[0, -1, 2],  # End Z
                color='red', marker='X', s=150, label="End Point")  # Red End

    ax2.view_init(elev=10, azim=0)
    ax2.set_title("Right Arm End-Effector Trajectories")
    ax2.set_xlabel("X")
    ax2.set_ylabel("Y")
    ax2.set_zlabel("Z")
    ax2.legend()

    plt.tight_layout()
    plt.show()


def filter_points_by_bounds(points, bounds_min, bounds_max, strict=True):
    """
    Filter points by taking only points within workspace bounds.
    """
    assert points.shape[1] == 3, "points must be (N, 3)"
    bounds_min = bounds_min.copy()
    bounds_max = bounds_max.copy()

    # print("candidate_keypoints (min):", points.min(axis=0))
    # print("candidate_keypoints (max):", points.max(axis=0))
    # print("bounds_min:", bounds_min)
    # print("bounds_max:", bounds_max)

    if not strict:
        bounds_min[:2] = bounds_min[:2] - 0.1 * (bounds_max[:2] - bounds_min[:2])
        bounds_max[:2] = bounds_max[:2] + 0.1 * (bounds_max[:2] - bounds_min[:2])
        bounds_min[2] = bounds_min[2] - 0.1 * (bounds_max[2] - bounds_min[2])
    within_bounds_mask = (
        (points[:, 0] >= bounds_min[0])
        & (points[:, 0] <= bounds_max[0])
        & (points[:, 1] >= bounds_min[1])
        & (points[:, 1] <= bounds_max[1])
        & (points[:, 2] >= bounds_min[2])
        & (points[:, 2] <= bounds_max[2])
    )
    return within_bounds_mask


@njit(cache=True, fastmath=True)
def batch_transform_points(points, transforms):
    """
    Apply multiple of transformation to point cloud, return results of individual transformations.
    Args:
        points: point cloud (N, 3).
        transforms: M 4x4 transformations (M, 4, 4).
    Returns:
        np.array: point clouds (M, N, 3).
    """
    assert transforms.shape[1:] == (4, 4), 'transforms must be of shape (M, 4, 4)'
    transformed_points = np.zeros((transforms.shape[0], points.shape[0], 3))
    for i in range(transforms.shape[0]):
        pos, R = transforms[i, :3, 3], transforms[i, :3, :3]
        transformed_points[i] = np.dot(points, R.T) + pos
    return transformed_points

# def pixel_to_3d_points(depth_image, intrinsics, extrinsics):
#     # Get the shape of the depth image
#     H, W = depth_image.shape
#
#     # Create a grid of (x, y) coordinates corresponding to each pixel in the image
#     i, j = np.meshgrid(np.arange(W), np.arange(H), indexing='xy')
#
#     # Unpack the intrinsic parameters
#     fx, fy = intrinsics[0, 0], intrinsics[1, 1]
#     cx, cy = intrinsics[0, 2], intrinsics[1, 2]
#
#     # Convert pixel coordinates to normalized camera coordinates
#     z = depth_image
#     x = (i - cx) * z / fx
#     y = (j - cy) * z / fy
#
#     # Stack the coordinates to form (H, W, 3)
#     camera_coordinates = np.stack((x, y, z), axis=-1)
#
#     # Reshape to (H*W, 3) for matrix multiplication
#     camera_coordinates = camera_coordinates.reshape(-1, 3)
#
#     # Convert to homogeneous coordinates (H*W, 4)
#     camera_coordinates_homogeneous = np.hstack((camera_coordinates, np.ones((camera_coordinates.shape[0], 1))))
#
#     # additional conversion to og convention
#     T_mod = np.array([[1., 0., 0., 0., ],
#               [0., -1., 0., 0.,],
#               [0., 0., -1., 0.,],
#               [0., 0., 0., 1.,]])
#     camera_coordinates_homogeneous = camera_coordinates_homogeneous @ T_mod
#
#     # Apply extrinsics to get world coordinates
#     # world_coordinates_homogeneous = camera_coordinates_homogeneous @ extrinsics.T
#     world_coordinates_homogeneous = T.pose_inv(extrinsics) @ (camera_coordinates_homogeneous.T)
#     world_coordinates_homogeneous = world_coordinates_homogeneous.T
#
#     # Convert back to non-homogeneous coordinates
#     world_coordinates = world_coordinates_homogeneous[:, :3] / world_coordinates_homogeneous[:, 3, np.newaxis]
#
#     # Reshape back to (H, W, 3)
#     world_coordinates = world_coordinates.reshape(H, W, 3)
#
#     return world_coordinates

def pixel_to_3d_points(depth_image, intrinsics, extrinsics):
    """
    Convert a depth image to 3D world coordinates using camera intrinsics and extrinsics.

    Args:
        depth_image (np.ndarray): Depth image of shape (H, W) or (H, W, 1), dtype can be uint16 (mm) or float32 (m).
        intrinsics (np.ndarray): 3x3 intrinsic matrix.
        extrinsics (np.ndarray): 4x4 extrinsic matrix (camera-to-world transform).

    Returns:
        np.ndarray: 3D points of shape (H, W, 3), in world coordinates.
    """
    # Ensure depth image is 2D
    if depth_image.ndim == 3 and depth_image.shape[2] == 1:
        depth_image = depth_image[:, :, 0]
    elif depth_image.ndim != 2:
        raise ValueError(f"Expected depth_image to be 2D or (H, W, 1), but got shape: {depth_image.shape}")

    np.savetxt("depth_values.txt", depth_image, fmt="%.3f")
    print("depth_image type:", depth_image.dtype)


    # Convert depth to meters
    if depth_image.dtype == np.uint16:
        invalid_mask = (depth_image == 0) | (depth_image == 65535)
        depth_image = depth_image.astype(np.float32) / 1000.0
        depth_image[invalid_mask] = 0.0  # 标记为无效点

    print("depth_image min, max:", depth_image.min(), depth_image.max())
    H, W = depth_image.shape

    # Create pixel coordinate grid
    i, j = np.meshgrid(np.arange(W), np.arange(H), indexing='xy')

    # Unpack intrinsics
    fx, fy = intrinsics.fx, intrinsics.fy
    cx, cy = intrinsics.ppx, intrinsics.ppy
    print("fx, fy, cx, cy:", fx, fy, cx, cy)

    # Project to camera coordinates
    z = depth_image
    x = (i - cx) * z / fx
    y = (j - cy) * z / fy

    print("x, y, z:", x[0, 0], y[0, 0], z[0, 0])

    # Stack into (H*W, 3)
    camera_coordinates = np.stack((x, y, z), axis=-1).reshape(-1, 3)

    # Homogeneous coordinates
    camera_coordinates_homogeneous = np.hstack((camera_coordinates, np.ones((camera_coordinates.shape[0], 1))))

    # Convert to OpenGL convention
    T_mod = np.array([
        [1., 0.,  0., 0.],
        [0., -1., 0., 0.],
        [0., 0., -1., 0.],
        [0., 0.,  0., 1.]
    ])
    camera_coordinates_homogeneous = camera_coordinates_homogeneous @ T_mod

    # Transform to world coordinates
    world_coordinates_homogeneous = T.pose_inv(extrinsics) @ camera_coordinates_homogeneous.T
    world_coordinates_homogeneous = world_coordinates_homogeneous.T

    # Convert to non-homogeneous
    world_coordinates = world_coordinates_homogeneous[:, :3] / world_coordinates_homogeneous[:, 3, np.newaxis]

    # Reshape to (H, W, 3)
    return world_coordinates.reshape(H, W, 3)